int gravity = 2000;
const int worlToPixelRatio = 10;
double initialVelocity = 30;
double acceleration = 1;
double accelerationIncrement = 1;
double baseAcceleration = 1;
int dayNightOffest = 1000;
double jumpVelocity = 850;
double minHurdleSpacing = 100;
